// example/src/components/SsoProviderButtons.vue
<script setup lang="ts">
import { onMounted, ref } from 'vue'
import { useAuthStore, type IdpOption } from '../stores/auth'

const emit = defineEmits<{ success: []; error: [message: string] }>()

const authStore = useAuthStore()
const providers = ref<IdpOption[]>([])
const ldapAlias = ref<string | null>(null)
const ldapUsername = ref('')
const ldapPassword = ref('')
const busy = ref(false)

onMounted(async () => {
  try {
    providers.value = await authStore.getIdpProviders()
  } catch {
    // No IdPs configured (or admin hasn't set any up yet) — render nothing, same as the
    // main app's SsoProviderButtons.tsx.
  }
})

function startLdap(alias: string) {
  ldapAlias.value = alias
  ldapUsername.value = ''
  ldapPassword.value = ''
}

async function submitLdap(alias: string) {
  busy.value = true
  try {
    await authStore.ldapLogin(alias, ldapUsername.value, ldapPassword.value)
    emit('success')
  } catch (err: any) {
    emit('error', err.response?.data?.error || err.message || 'LDAP sign-in failed')
  } finally {
    busy.value = false
  }
}
</script>

<template>
  <div v-if="providers.length" class="sso-providers">
    <div class="separator mt-8 mb-8">
      <span class="separator-text">or sign in with an identity provider</span>
    </div>

    <div class="form-group">
      <template v-for="p in providers.filter(p => p.type !== 'ldap')" :key="p.alias">
        <a
          :href="authStore.federationLoginUrl(p.alias, p.type as 'saml' | 'oidc')"
          class="btn btn-secondary"
          style="width: 100%; margin-bottom: var(--space-3); height: 48px;"
        >
          {{ p.displayName }} ({{ p.type.toUpperCase() }})
        </a>
      </template>

      <template v-for="p in providers.filter(p => p.type === 'ldap')" :key="p.alias">
        <form v-if="ldapAlias === p.alias" class="ldap-form" @submit.prevent="submitLdap(p.alias)">
          <input v-model="ldapUsername" type="text" class="form-input mb-3" required placeholder="LDAP username" autofocus />
          <input v-model="ldapPassword" type="password" class="form-input mb-3" required placeholder="LDAP password" />
          <div style="display: flex; gap: var(--space-3);">
            <button type="button" class="btn btn-secondary" style="flex: 1; height: 40px;" @click="ldapAlias = null">Cancel</button>
            <button type="submit" class="btn btn-primary" style="flex: 1; height: 40px;" :disabled="busy">
              {{ busy ? 'Signing in...' : 'Sign In' }}
            </button>
          </div>
        </form>
        <button
          v-else
          type="button"
          class="btn btn-secondary"
          style="width: 100%; margin-bottom: var(--space-3); height: 48px;"
          @click="startLdap(p.alias)"
        >
          {{ p.displayName }} (LDAP)
        </button>
      </template>
    </div>

    <p class="text-xs text-muted mb-0">
      SAML/OIDC providers redirect through the main app (federation callbacks are same-origin
      only) and hand you back there once signed in — only LDAP completes inside this demo.
    </p>
  </div>
</template>

<style scoped>
.ldap-form { border: 1px solid var(--slate-100); border-radius: var(--radius-lg); padding: var(--space-4); margin-bottom: var(--space-3); }
</style>

// src/components/SsoProviderButtons.tsx
import { useEffect, useState } from 'react';
import { parseApiResponse, isSuccess } from '../utils/fetch';
import type { AuthUser } from '../types/user';

interface IdpOption {
  alias: string;
  type: 'saml' | 'oidc' | 'ldap';
  displayName: string;
}

interface LdapLoginResult {
  access_token: string;
  refresh_token: string;
  session_id?: string;
  user?: AuthUser;
}

export function SsoProviderButtons({
  redirect,
  onLdapSuccess,
  onError,
}: {
  redirect?: string;
  onLdapSuccess: (data: LdapLoginResult) => void;
  onError: (message: string) => void;
}) {
  const [providers, setProviders] = useState<IdpOption[]>([]);
  const [ldapAlias, setLdapAlias] = useState<string | null>(null);
  const [ldapUsername, setLdapUsername] = useState('');
  const [ldapPassword, setLdapPassword] = useState('');
  const [busy, setBusy] = useState(false);

  useEffect(() => {
    fetch('/api/auth/idps')
      .then(res => parseApiResponse<{ providers: IdpOption[] }>(res))
      .then(result => {
        if (isSuccess(result) && result.data) setProviders(result.data.providers);
      })
      .catch(() => {});
  }, []);

  if (providers.length === 0) return null;

  const tenantId = typeof window !== 'undefined' ? localStorage.getItem('tenant_id') : null;

  function federationHref(alias: string, type: 'saml' | 'oidc') {
    const params = new URLSearchParams();
    if (redirect) params.set('redirect', redirect);
    if (tenantId) params.set('tenant_id', tenantId);
    const qs = params.toString();
    return `/api/federation/${alias}/${type}/login${qs ? `?${qs}` : ''}`;
  }

  async function handleLdapSubmit(e: React.FormEvent) {
    e.preventDefault();
    if (!ldapAlias) return;
    setBusy(true);
    try {
      const res = await fetch(`/api/federation/${ldapAlias}/ldap/login`, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          ...(tenantId ? { 'X-Tenant-ID': tenantId } : {}),
        },
        body: JSON.stringify({ username: ldapUsername, password: ldapPassword }),
      });
      const result = await parseApiResponse<LdapLoginResult>(res);
      if (isSuccess(result) && result.data) {
        onLdapSuccess(result.data);
      } else {
        onError(result.error || 'Sign-in failed');
      }
    } finally {
      setBusy(false);
    }
  }

  return (
    <div className="mt-6">
      <div className="relative">
        <div className="absolute inset-0 flex items-center">
          <div className="w-full border-t border-zinc-300 dark:border-zinc-700" />
        </div>
        <div className="relative flex justify-center text-sm">
          <span className="px-2 bg-white dark:bg-zinc-900 text-zinc-500 dark:text-zinc-400">Or sign in with</span>
        </div>
      </div>

      <div className="mt-4 space-y-2">
        {providers.filter(p => p.type !== 'ldap').map(p => (
          <a
            key={p.alias}
            href={federationHref(p.alias, p.type as 'saml' | 'oidc')}
            className="w-full flex justify-center items-center gap-2 py-2 px-4 border border-zinc-300 dark:border-zinc-700 rounded-md shadow-sm text-sm font-medium text-zinc-700 dark:text-zinc-300 bg-white dark:bg-zinc-800 hover:bg-zinc-50 dark:hover:bg-zinc-700"
          >
            {p.displayName}
          </a>
        ))}

        {providers.filter(p => p.type === 'ldap').map(p => (
          <div key={p.alias}>
            {ldapAlias === p.alias ? (
              <form onSubmit={handleLdapSubmit} className="space-y-2 border border-zinc-200 dark:border-zinc-700 rounded-md p-3">
                <input
                  type="text"
                  required
                  autoFocus
                  placeholder="Username"
                  value={ldapUsername}
                  onChange={(e) => setLdapUsername(e.target.value)}
                  className="block w-full px-3 py-2 border border-zinc-300 dark:border-zinc-700 dark:bg-zinc-800 dark:text-white rounded-md shadow-sm sm:text-sm"
                />
                <input
                  type="password"
                  required
                  placeholder="Password"
                  value={ldapPassword}
                  onChange={(e) => setLdapPassword(e.target.value)}
                  className="block w-full px-3 py-2 border border-zinc-300 dark:border-zinc-700 dark:bg-zinc-800 dark:text-white rounded-md shadow-sm sm:text-sm"
                />
                <div className="flex justify-end gap-2">
                  <button type="button" onClick={() => setLdapAlias(null)} className="text-sm text-zinc-500 hover:text-zinc-700 dark:text-zinc-400">
                    Cancel
                  </button>
                  <button type="submit" disabled={busy} className="py-1.5 px-3 rounded-md text-sm font-medium text-white bg-indigo-600 hover:bg-indigo-700 disabled:opacity-50">
                    Sign in
                  </button>
                </div>
              </form>
            ) : (
              <button
                onClick={() => { setLdapAlias(p.alias); setLdapUsername(''); setLdapPassword(''); }}
                className="w-full flex justify-center items-center gap-2 py-2 px-4 border border-zinc-300 dark:border-zinc-700 rounded-md shadow-sm text-sm font-medium text-zinc-700 dark:text-zinc-300 bg-white dark:bg-zinc-800 hover:bg-zinc-50 dark:hover:bg-zinc-700"
              >
                {p.displayName}
              </button>
            )}
          </div>
        ))}
      </div>
    </div>
  );
}
